# SubNav
menu:
  #å…³äºæˆ‘: /2014/aboutme/
  å‹é“¾: /2014/friends/
subnav:
  github: "https://github.com/Yokeso"
  #weibo: "http://weibo.com/u/888888888"
  zhihu: "https://www.zhihu.com/people/xing-chen-da-hai-41-66"
  email: "MailTo:460063539@qq.com"
  sf: "https://segmentfault.com/u/555555"
  rss: "/atom.xml"

description: Talk is Cheap,Show Me Your Code

# SEO
seo_keywords: hexo,ä¸ªäººåšå®¢,blog,Yokeso
seo_description: Yokesoçš„ä¸ªäººåšå®¢

favicon: /favicon.ico

#ä½ çš„å¤´åƒurl
avatar: 
    https://pic3.zhimg.com/v2-8bcbe433a7a4ea0edc4f010bd12c3294_r.jpg

leftBackground:
  - https://pic1.zhimg.com/80/v2-e1d7e8f6caafa74c0c0088ca9b8d131c_720w.jpg
  - https://pic4.zhimg.com/80/v2-d0af3f5e4200c789fd01117c4192dbff_720w.jpg
  - https://pic1.zhimg.com/80/v2-5ebef8621862d0b3b6dd7edc02de0528_720w.jpg
  - https://pic1.zhimg.com/80/v2-efdd002e34ce41dc5c44699efac5f174_720w.jpg
  - https://pic4.zhimg.com/80/v2-5d632079a82145fac43ab4a59cdde97f_720w.jpg

# å±•ç¤ºæ›´æ–°æ—¶é—´
display_updated: true

# æ–‡ç« é¡µçš„å…³äºè½¬è½½é“¾æ¥
copyright_url: https://888.com/index.html

# åº•éƒ¨çš„å¤‡æ¡ˆä¿¡æ¯ç­‰
copyright_date: 2019-2020
beian_info: Yokesoçš„åšå®¢

# Online contact
daovoice: true
daovoice_app_id: 1d3cd644 #è¾“å…¥app_id

# Data statistics
baidu_analytics: true
baidu_analytics_code: awwssw1snsnsnn1ndndnndnd99j

#Comments
# https://github.com/gitalk/gitalk
gitalk: true
gitalk_clientID: 1a64a259684b5713abf1
gitalk_clientSecret: fbeb79e4e46138f88b662872e0c1242e0aed2a03
gitalk_repo: Yokeso.github.io
gitalk_owner: Yokeso
gitalk_admin: Yokeso
# æ˜¯å¦å¯ç”¨è¯„è®ºæ¡†çš„å…¨å±é®ç½©æ•ˆæœ
gitalk_distractionFreeMode: false

# Console
console: true
console_color: '#6190e8'
console_config:
  - '\næ¬¢è¿è®¿é—® https://yokeso.github.io ï¼Œå›´è§‚Yokesoçš„åšå®¢(ã¥ï½¡â—•â€¿â€¿â—•ï½¡)ã¥ï¼\n'
  - '\næœ¬åšå®¢ä½¿ç”¨ %cHexo%c æ­å»ºï¼Œåšå®¢ä¸»é¢˜ä¸ºYokesoä¿®æ”¹çš„ %chexo-themes-yearn%c ~~~ ğŸ‰ğŸ‰ğŸ‰ \n\næºç  https://github.com/Youthink/hexo-themes-yearn \n\nå¦‚æœå–œæ¬¢å¯ä»¥ star æ”¯æŒä¸€ä¸‹ â¤ï¸~\n'

# é•¿æ—¶é—´æœªæ›´æ–°çš„åšæ–‡æ˜¾ç¤ºæé†’
overdue_auto_all: false
overdue_remind: æœ¬æ–‡æœ€åæ›´æ–°äº$dayå¤©å‰ï¼Œæ–‡ä¸­æ‰€æè¿°çš„ä¿¡æ¯å¯èƒ½å·²å‘ç”Ÿæ”¹å˜ã€‚

